//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Data.Visualization.Engine;

namespace Microsoft.Data.Visualization.VisualizationControls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AerialWithLabelsEndPoint {
            get {
                return ((string)(this["AerialWithLabelsEndPoint"]));
            }
            set {
                this["AerialWithLabelsEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AerialWithoutLabelsEndPoint {
            get {
                return ((string)(this["AerialWithoutLabelsEndPoint"]));
            }
            set {
                this["AerialWithoutLabelsEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RoadWithoutLabelsEndPoint {
            get {
                return ((string)(this["RoadWithoutLabelsEndPoint"]));
            }
            set {
                this["RoadWithoutLabelsEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BingLogoAerialEndPoint {
            get {
                return ((string)(this["BingLogoAerialEndPoint"]));
            }
            set {
                this["BingLogoAerialEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BingLogoEndPoint {
            get {
                return ((string)(this["BingLogoEndPoint"]));
            }
            set {
                this["BingLogoEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CombinedLogoAerialEndPoint {
            get {
                return ((string)(this["CombinedLogoAerialEndPoint"]));
            }
            set {
                this["CombinedLogoAerialEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CombinedLogoEndPoint {
            get {
                return ((string)(this["CombinedLogoEndPoint"]));
            }
            set {
                this["CombinedLogoEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RoadWithLabelsEndPoint {
            get {
                return ((string)(this["RoadWithLabelsEndPoint"]));
            }
            set {
                this["RoadWithLabelsEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GeocodingEndPoint {
            get {
                return ((string)(this["GeocodingEndPoint"]));
            }
            set {
                this["GeocodingEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowProfilerInfo {
            get {
                return ((bool)(this["ShowProfilerInfo"]));
            }
            set {
                this["ShowProfilerInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public GraphicsLevel GraphicsLevel
        {
            get {
                return ((GraphicsLevel)(this["GraphicsLevel"]));
            }
            set {
                this["GraphicsLevel"] = value;
            }
        }
    }
}
