//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The Power Map field name is not valid. To create a Power Map exploration, you must use data that is organized as a table with labeled columns. If you are changing the name of a  Power Map field, you must type a new name for the field. 的本地化字符串。
        /// </summary>
        internal static string AddToModelGapInHeader {
            get {
                return ResourceManager.GetString("AddToModelGapInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map cannot handle columns that have been hidden via PowerPivot. Please unhide these columns in PowerPivot and try again. 的本地化字符串。
        /// </summary>
        internal static string AddToModelHiddenTableColumns {
            get {
                return ResourceManager.GetString("AddToModelHiddenTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data source reference not valid. 的本地化字符串。
        /// </summary>
        internal static string AddToModelInvalidDataSource {
            get {
                return ResourceManager.GetString("AddToModelInvalidDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map requires at least two rows of source data. The first row is treated as headers. You cannot use this command on a selection in only one row. 的本地化字符串。
        /// </summary>
        internal static string AddToModelNotEnoughRowsSelected {
            get {
                return ResourceManager.GetString("AddToModelNotEnoughRowsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map encountered an error and cannot be launched. Please check your internet connectivity and try again (Status Code: {0}). 的本地化字符串。
        /// </summary>
        internal static string BingGeoPolError {
            get {
                return ResourceManager.GetString("BingGeoPolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map encountered an error while contacting Microsoft Bing mapping services. Functionality may be limited. (Status Code: {0}). 的本地化字符串。
        /// </summary>
        internal static string BingGeoPolErrorUseExistingEndpoints {
            get {
                return ResourceManager.GetString("BingGeoPolErrorUseExistingEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We are sorry, Power Map can not be used in your country/region at this time. 的本地化字符串。
        /// </summary>
        internal static string BingGeoPolLocationNotSupported {
            get {
                return ResourceManager.GetString("BingGeoPolLocationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map cannot contact Microsoft Bing mapping services. Please check your internet connectivity and try again (Status Code: {0}). 的本地化字符串。
        /// </summary>
        internal static string BingGeoPolServerNotReachable {
            get {
                return ResourceManager.GetString("BingGeoPolServerNotReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map will use the Gregorian calendar. 的本地化字符串。
        /// </summary>
        internal static string CalendarChanged {
            get {
                return ResourceManager.GetString("CalendarChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map has encountered an error and it needs to close. 的本地化字符串。
        /// </summary>
        internal static string ClosingOnError {
            get {
                return ResourceManager.GetString("ClosingOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map has encountered an error and it needs to close.
        ///Power Map can collect information about the error and create an email which you will be able to send to Microsoft and help us fix this problem. Do you want do this? 的本地化字符串。
        /// </summary>
        internal static string ClosingOnErrorWithException {
            get {
                return ResourceManager.GetString("ClosingOnErrorWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tour {0} 的本地化字符串。
        /// </summary>
        internal static string DefaultTourName {
            get {
                return ResourceManager.GetString("DefaultTourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t undo deleting tours. Do you want to delete this tour? 的本地化字符串。
        /// </summary>
        internal static string DeleteTourMessage {
            get {
                return ResourceManager.GetString("DeleteTourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Tour 的本地化字符串。
        /// </summary>
        internal static string DeleteTourTitle {
            get {
                return ResourceManager.GetString("DeleteTourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate 的本地化字符串。
        /// </summary>
        internal static string DuplicateCommand {
            get {
                return ResourceManager.GetString("DuplicateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot initialize DirectX. Confirm that your hardware supports DirectX 10 or later and that you have the latest video card driver installed. 的本地化字符串。
        /// </summary>
        internal static string EngineError {
            get {
                return ResourceManager.GetString("EngineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thank you for submitting this error information to Microsoft. We appreciate your help!
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorEmailBody {
            get {
                return ResourceManager.GetString("ErrorEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map Error 的本地化字符串。
        /// </summary>
        internal static string ErrorEmailSubject {
            get {
                return ResourceManager.GetString("ErrorEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Excel 的本地化字符串。
        /// </summary>
        internal static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Currently Open) 的本地化字符串。
        /// </summary>
        internal static string ManageDialogCurrentlyOpen {
            get {
                return ResourceManager.GetString("ManageDialogCurrentlyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Tour 的本地化字符串。
        /// </summary>
        internal static string ManageDialogNewTourButton {
            get {
                return ResourceManager.GetString("ManageDialogNewTourButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open... 的本地化字符串。
        /// </summary>
        internal static string ManageDialogOpen {
            get {
                return ResourceManager.GetString("ManageDialogOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to... 的本地化字符串。
        /// </summary>
        internal static string ManageDialogSwitchTo {
            get {
                return ResourceManager.GetString("ManageDialogSwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Power Map 的本地化字符串。
        /// </summary>
        internal static string ManageDialogTitle {
            get {
                return ResourceManager.GetString("ManageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string ManageToursWindow_CloseTooltip {
            get {
                return ResourceManager.GetString("ManageToursWindow_CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete this tour. 的本地化字符串。
        /// </summary>
        internal static string ManageToursWindow_DeleteTourTooltip {
            get {
                return ResourceManager.GetString("ManageToursWindow_DeleteTourTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new tour. 的本地化字符串。
        /// </summary>
        internal static string ManageToursWindow_NewTourTooltip {
            get {
                return ResourceManager.GetString("ManageToursWindow_NewTourTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open this tour to edit or play it. 的本地化字符串。
        /// </summary>
        internal static string ManageToursWindow_TourTooltip {
            get {
                return ResourceManager.GetString("ManageToursWindow_TourTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There appears to be a problem with your data schema. This error may be caused by superscripts or subscripts in a column header. If so, please remove them, refresh the workbook connection, and try again. Workbook connections can be refreshed with Excel&apos;s Connections dialog in the DATA tab. 的本地化字符串。
        /// </summary>
        internal static string ModelSuperscriptError {
            get {
                return ResourceManager.GetString("ModelSuperscriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close the launch power map dialog. 的本地化字符串。
        /// </summary>
        internal static string NarratorTourManager_Close {
            get {
                return ResourceManager.GetString("NarratorTourManager_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0} tour delete&apos; 的本地化字符串。
        /// </summary>
        internal static string NarratorTourManager_Delete {
            get {
                return ResourceManager.GetString("NarratorTourManager_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0} tour&apos; 的本地化字符串。
        /// </summary>
        internal static string NarratorTourManager_tour {
            get {
                return ResourceManager.GetString("NarratorTourManager_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tour Name 的本地化字符串。
        /// </summary>
        internal static string NoTourName {
            get {
                return ResourceManager.GetString("NoTourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map needs more resources to complete this operation. 
        ///
        ///Learn more about handling large datasets with Power Map on Office.com. 的本地化字符串。
        /// </summary>
        internal static string OOMError {
            get {
                return ResourceManager.GetString("OOMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map needs more resources to complete this operation. 
        ///
        ///For the best performance with Power Map, we recommend switching to the 64-bit version of Microsoft Office. Learn more about handling large datasets with Power Map on Office.com. 的本地化字符串。
        /// </summary>
        internal static string OOMError32 {
            get {
                return ResourceManager.GetString("OOMError32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string OpenCommand {
            get {
                return ResourceManager.GetString("OpenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        internal static string PlayCommand {
            get {
                return ResourceManager.GetString("PlayCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Power Map for Excel 的本地化字符串。
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map encountered an error. If the workbook has been protected, please unprotect it, save it and launch Power Map again. 的本地化字符串。
        /// </summary>
        internal static string ProtectedWorkbookError {
            get {
                return ResourceManager.GetString("ProtectedWorkbookError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map encountered an error. Please try your last action again. 的本地化字符串。
        /// </summary>
        internal static string RetryAction {
            get {
                return ResourceManager.GetString("RetryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Map encountered an error. If you are editing a cell, please exit cell edit mode before retrying your last action. 的本地化字符串。
        /// </summary>
        internal static string RetryActionAfterEditDone {
            get {
                return ResourceManager.GetString("RetryActionAfterEditDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, you are trying to open an older tour that we no longer support. Please delete the tour and recreate it. 的本地化字符串。
        /// </summary>
        internal static string SerializationError {
            get {
                return ResourceManager.GetString("SerializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy of {0} 的本地化字符串。
        /// </summary>
        internal static string TourDuplicateName {
            get {
                return ResourceManager.GetString("TourDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We are sorry. Power Map encountered an error opening the tour. 的本地化字符串。
        /// </summary>
        internal static string TourNotFound {
            get {
                return ResourceManager.GetString("TourNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This tour can’t be opened with your version of Power Map. An upgrade should fix the problem. 的本地化字符串。
        /// </summary>
        internal static string TourXmlIncompatible {
            get {
                return ResourceManager.GetString("TourXmlIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This tour was created with a newer version of Power Map. Some features in this tour may not work in this version of Power Map. If you save this workbook, you may lose those features. 的本地化字符串。
        /// </summary>
        internal static string TourXmlVersionHigher {
            get {
                return ResourceManager.GetString("TourXmlVersionHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open your default email client. 的本地化字符串。
        /// </summary>
        internal static string UnableToSendEmail {
            get {
                return ResourceManager.GetString("UnableToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - Microsoft Power Map for Excel 的本地化字符串。
        /// </summary>
        internal static string VisualizationTitle {
            get {
                return ResourceManager.GetString("VisualizationTitle", resourceCulture);
            }
        }
    }
}
